name: DevSecOps CICD workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security-scan-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install & Run Gitleaks
        run: |
          sudo apt-get update
          sudo apt-get install -y gitleaks
          gitleaks detect --source . --report-format json --report-path=gitleaks-report.json

  build:
    runs-on: ubuntu-latest
    needs: [security-scan-gitleaks]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore
        run: dotnet restore Time.Api.sln

      - name: Build
        run: dotnet build Time.Api.sln --configuration Release --no-restore

