name: DevSecOps CICD workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0

      - name: Restore
        run: dotnet restore Time.Api.sln

      - name: Build
        run: dotnet build Time.Api.sln --configuration Release --no-restore

